insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (1, 'Mile', 'Goodbairn', 'Goalkeeper', 'Muxagata', 10663);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (2, 'Ruperto', 'Furmage', 'Midfielder', 'Sankanan', 16981);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (3, 'Nevil', 'Trayhorn', 'Defender', 'Paris 10', 12587);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (4, 'Debora', 'Stirland', 'Defender', 'Kunwi', 15923);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (5, 'Regina', 'Scandroot', 'Midfielder', 'Wilga', 11137);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (6, 'Bette', 'Bazylets', 'Defender', 'Injīl', 14366);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (7, 'Sophronia', 'Walewski', 'Attacker', 'Sofifi', 10828);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (8, 'Yoshi', 'McMichan', 'Attacker', 'Baoping', 7568);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (9, 'Sheena', 'Retallick', 'Defender', 'Hobonio', 15092);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (10, 'Alaster', 'Coolson', 'Defender', 'Santa Bárbara d''Oeste', 10229);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (11, 'Dare', 'Lyddy', 'Defender', 'Długosiodło', 11919);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (12, 'Jolene', 'Ciani', 'Attacker', 'Panineungan', 10573);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (13, 'Odessa', 'Sarjent', 'Goalkeeper', 'Bununu Kasa', 17666);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (14, 'Wendye', 'Sich', 'Attacker', 'Erie', 8175);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (15, 'Lida', 'Isaacs', 'Goalkeeper', 'Zhangjiabao', 8539);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (16, 'Anthia', 'Kubec', 'Midfielder', 'Belfast', 10711);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (17, 'Amabelle', 'Berzin', 'Midfielder', 'San Pedro del Paraná', 9586);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (18, 'Loella', 'Guerre', 'Goalkeeper', 'Hepu', 10142);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (19, 'Timmie', 'Thorowgood', 'Goalkeeper', 'Sulbiny Górne', 16172);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (20, 'Percy', 'Elkins', 'Defender', 'Bogorejo', 7132);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (21, 'Nani', 'Royds', 'Attacker', 'Haapsalu', 16989);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (22, 'Dorine', 'Andriulis', 'Goalkeeper', 'Tuanjie', 5900);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (23, 'Freddy', 'Pitkins', 'Attacker', 'Corrego Grande', 6279);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (24, 'Rebbecca', 'McGeachy', 'Midfielder', 'Bartsrashen', 13951);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (25, 'Buiron', 'Gonzalez', 'Midfielder', 'Pamplona/Iruña', 14341);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (26, 'Evania', 'De Cristoforo', 'Defender', 'Yangxiang', 6411);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (27, 'Katinka', 'Meakes', 'Attacker', 'Shinpokh', 9340);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (28, 'Sandra', 'Sturridge', 'Goalkeeper', 'Turenki', 17866);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (29, 'Horatius', 'Atger', 'Defender', 'Paris 11', 16298);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (30, 'Chelsae', 'Ridgedell', 'Attacker', 'Barat', 6617);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (31, 'Ulises', 'Munford', 'Defender', 'Wenquan', 5218);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (32, 'Honey', 'Rubertis', 'Midfielder', 'Chigan', 5437);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (33, 'Devi', 'Greeding', 'Defender', 'Santo António', 6542);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (34, 'Shina', 'Fazackerley', 'Goalkeeper', 'Raglan', 19886);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (35, 'Bonnibelle', 'Bransby', 'Defender', 'Nar''yan-Mar', 10330);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (36, 'Keven', 'Lowmass', 'Attacker', 'Situsari', 17180);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (37, 'Olivero', 'Wilmore', 'Midfielder', 'Jāti', 6471);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (38, 'Simone', 'Deeble', 'Defender', 'Medveditskiy', 12387);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (39, 'Jan', 'Liversage', 'Goalkeeper', 'Kanekomachi', 19275);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (40, 'Geoffrey', 'Pickburn', 'Attacker', 'Novopskov', 19135);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (41, 'Elbert', 'Capelen', 'Midfielder', 'Karbunara e Vogël', 9536);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (42, 'Ulrika', 'Jellis', 'Defender', 'Sindang', 6878);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (43, 'Holly-anne', 'Reede', 'Defender', 'Guanchao', 4499);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (44, 'Addia', 'Davio', 'Midfielder', 'Taoyuan', 16472);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (45, 'Corney', 'Membry', 'Defender', 'Huanggang', 13624);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (46, 'Maren', 'Braidman', 'Attacker', 'Murakami', 11931);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (47, 'Cleo', 'Copcutt', 'Goalkeeper', 'Mloko', 13705);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (48, 'Yasmeen', 'Saltern', 'Attacker', 'Kamal', 5201);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (49, 'Brennan', 'Leatherborrow', 'Midfielder', 'Divinópolis', 14838);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (50, 'Arleyne', 'Cheek', 'Goalkeeper', 'Lenningen', 6006);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (51, 'Dan', 'McCrie', 'Attacker', 'Loreto', 4340);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (52, 'Drugi', 'Corbert', 'Defender', 'Monastyryshche', 4512);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (53, 'Dalt', 'Sparkwell', 'Goalkeeper', 'São João dos Patos', 19431);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (54, 'Emilia', 'Dorkin', 'Midfielder', 'Buffalo', 11393);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (55, 'Erskine', 'Tuckwood', 'Defender', 'Seseng', 6615);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (56, 'Celine', 'Pendergast', 'Midfielder', 'Gudauta', 19604);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (57, 'Pembroke', 'Bolin', 'Goalkeeper', 'Caotang', 14778);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (58, 'Jakie', 'Dowe', 'Attacker', 'Huanren', 9810);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (59, 'Jermayne', 'Sayes', 'Attacker', 'Javhlant', 16812);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (60, 'Mike', 'Irwin', 'Defender', 'Stockholm', 6610);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (61, 'Gerri', 'Hegges', 'Attacker', 'Tīkāpur', 11692);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (62, 'Carmelle', 'Hadley', 'Midfielder', 'Boshchorbogh', 9470);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (63, 'Diana', 'Guillon', 'Defender', 'Bla', 8735);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (64, 'Rocky', 'Eyres', 'Goalkeeper', 'Longmen', 4293);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (65, 'Jude', 'Schonfelder', 'Goalkeeper', 'Spartanburg', 13672);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (66, 'Cristi', 'MacAless', 'Goalkeeper', 'Lingbei', 18982);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (67, 'Rafe', 'Passy', 'Defender', 'Mersam', 6388);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (68, 'Elita', 'Bailiss', 'Defender', 'Hortolândia', 10506);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (69, 'Giovanna', 'Gieves', 'Midfielder', 'Tupambaé', 16201);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (70, 'Blanche', 'Bletcher', 'Goalkeeper', 'Sala', 18294);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (71, 'Obidiah', 'Mounch', 'Defender', 'Dalarik', 4946);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (72, 'Kameko', 'Hooks', 'Goalkeeper', 'Dallas', 15035);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (73, 'Celine', 'Mattacks', 'Attacker', 'Sipirok', 11524);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (74, 'Minda', 'Wearn', 'Attacker', 'Speightstown', 5296);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (75, 'Lars', 'Shedd', 'Midfielder', 'Miami', 10684);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (76, 'Guillermo', 'Gurry', 'Goalkeeper', 'Pendiqing', 10522);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (77, 'Evey', 'Peret', 'Goalkeeper', 'Mazongling', 11867);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (78, 'Anthiathia', 'Bulloch', 'Defender', 'Capâo Bonito', 5368);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (79, 'Yelena', 'Masi', 'Defender', 'Bronx', 5180);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (80, 'Horatius', 'MacEveley', 'Goalkeeper', 'Kesambilerenkrajan', 8222);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (81, 'Clarabelle', 'Dougal', 'Midfielder', 'Tucson', 13232);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (82, 'Shamus', 'Hurdis', 'Midfielder', 'Veselí nad Lužnicí', 19031);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (83, 'Kathryne', 'Nyles', 'Midfielder', 'Liqiao', 19077);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (84, 'Jenda', 'Mapplebeck', 'Midfielder', 'Kampungtengah', 5278);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (85, 'Birgit', 'Reast', 'Midfielder', 'Curahpacul Satu', 15857);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (86, 'Fredelia', 'Blincowe', 'Defender', 'Tromsø', 18340);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (87, 'Rogers', 'Baythorp', 'Attacker', 'Ra-ngae', 7776);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (88, 'Bryana', 'Rault', 'Defender', 'Zouma', 19165);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (89, 'Francesco', 'Danjoie', 'Attacker', 'Białogard', 9489);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (90, 'Rustie', 'Dietzler', 'Goalkeeper', 'Bucu Kidul', 13839);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (91, 'Wyatan', 'Wilstead', 'Goalkeeper', 'Zhongzhai', 15984);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (92, 'Loralee', 'Snellman', 'Midfielder', 'Najiaying', 16418);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (93, 'Borden', 'Rix', 'Defender', 'Davyd-Haradok', 5989);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (94, 'Teddi', 'Brodley', 'Attacker', 'Světlá nad Sázavou', 8371);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (95, 'Minnie', 'Wager', 'Goalkeeper', 'Amapala', 5958);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (96, 'Cynthie', 'Middlemiss', 'Goalkeeper', 'Andahuaylillas', 4818);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (97, 'Kaile', 'Tricker', 'Defender', 'Shimen', 19449);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (98, 'Bernice', 'Baccus', 'Goalkeeper', 'Lancaster', 5028);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (99, 'Warde', 'Chazette', 'Midfielder', 'Tianmen', 11725);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (100, 'Laurent', 'Paudin', 'Attacker', 'Brumadinho', 4606);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (101, 'Dottie', 'Kleinpeltz', 'Attacker', 'Karangdawa Barat', 10472);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (102, 'Bonita', 'Bossingham', 'Defender', 'Ukrainka', 11209);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (103, 'Jammie', 'Pharo', 'Attacker', 'Leubatang', 19212);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (104, 'Shawna', 'Oneil', 'Attacker', 'Shatki', 16394);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (105, 'Cornie', 'Tackle', 'Goalkeeper', 'Atlantis', 8605);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (106, 'Marlin', 'Brookshaw', 'Midfielder', 'Lizhai', 14688);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (107, 'Cami', 'Strooband', 'Midfielder', 'Baiyin', 11262);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (108, 'Bob', 'Fendt', 'Goalkeeper', 'Novoul’yanovsk', 4256);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (109, 'Abraham', 'Pelerin', 'Midfielder', 'Dmitriyevskoye', 5031);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (110, 'Adela', 'Swapp', 'Defender', 'Lovran', 5106);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (111, 'Greta', 'Bridden', 'Defender', 'Yatsuomachi-higashikumisaka', 12003);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (112, 'Bert', 'Reedman', 'Defender', 'Jiaoziya', 13100);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (113, 'Norrie', 'Woodeson', 'Midfielder', 'Sacramento', 11384);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (114, 'Dennet', 'Matthews', 'Defender', 'Bečej', 15981);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (115, 'Burt', 'Gumey', 'Defender', 'Guotan', 8420);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (116, 'Kaye', 'Leng', 'Goalkeeper', 'Heping', 15375);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (117, 'Dorris', 'Ormond', 'Goalkeeper', 'Gunungkendeng', 14785);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (118, 'Merissa', 'Jimenez', 'Defender', 'Portela', 9678);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (119, 'Abramo', 'Gelardi', 'Midfielder', 'Gengqing', 14778);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (120, 'Cinnamon', 'Dolbey', 'Defender', 'Gambarjati', 19818);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (121, 'Diane-marie', 'Pittle', 'Attacker', 'Yuncao', 8828);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (122, 'Martyn', 'Kingswold', 'Defender', 'Glinka', 4974);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (123, 'Vonny', 'Van Oord', 'Attacker', 'Allanridge', 4534);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (124, 'Korney', 'Lown', 'Goalkeeper', 'Brazzaville', 4955);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (125, 'Chiquia', 'Wescott', 'Goalkeeper', 'Arauca', 17756);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (126, 'Karlens', 'Blackburne', 'Midfielder', 'Bulod', 12338);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (127, 'Larisa', 'De La Coste', 'Defender', 'Aytos', 15072);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (128, 'Shalne', 'Hurworth', 'Goalkeeper', 'Noveleta', 9990);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (129, 'Renate', 'Duval', 'Attacker', 'Casa Nova', 4162);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (130, 'Morgan', 'Higbin', 'Goalkeeper', 'Xuedian', 6279);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (131, 'Georgeanne', 'Worcester', 'Attacker', 'Ambam', 8018);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (132, 'Paolina', 'Abramowitz', 'Attacker', 'Sidzina', 10133);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (133, 'Sanford', 'McGeachey', 'Attacker', 'Skolkovo', 8978);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (134, 'Annmaria', 'Dougan', 'Attacker', 'Yonezawa', 6704);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (135, 'Jerrold', 'Eton', 'Midfielder', 'Busay', 19118);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (136, 'Colet', 'Presslie', 'Defender', 'Paine', 5195);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (137, 'Randy', 'Furness', 'Defender', 'San Vicente de Bique', 6023);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (138, 'Avery', 'Ellaman', 'Defender', 'San Antonio', 14001);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (139, 'Bryan', 'Corker', 'Midfielder', 'Slavyanovo', 15713);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (140, 'Gertruda', 'Romanetti', 'Attacker', 'Wróblew', 16311);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (141, 'Patricia', 'Challis', 'Defender', 'New-Richmond', 15759);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (142, 'Salomone', 'Reeves', 'Midfielder', 'El Hajeb', 12681);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (143, 'Marty', 'Rintoul', 'Goalkeeper', 'Paraguaçu', 15716);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (144, 'James', 'Kermode', 'Attacker', 'Huanza', 17269);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (145, 'Pierrette', 'Godfray', 'Midfielder', 'Várzea de Sintra', 5303);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (146, 'Imojean', 'Murford', 'Defender', 'Embu', 15753);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (147, 'Tabbi', 'Bleasdille', 'Goalkeeper', 'Leipzig', 17418);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (148, 'Wilden', 'Coping', 'Defender', 'Krasnolesnyy', 19224);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (149, 'Linn', 'Skokoe', 'Attacker', 'Enrile', 12345);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (150, 'Gabriella', 'Elgie', 'Midfielder', 'Västervik', 12018);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (151, 'Marillin', 'Giraldo', 'Defender', 'Reggio Calabria', 4973);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (152, 'Seline', 'Aleksandrov', 'Midfielder', 'Yaguajay', 13072);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (153, 'Haskel', 'Rene', 'Attacker', 'Romans-sur-Isère', 16534);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (154, 'Federico', 'Bartolic', 'Goalkeeper', 'Praia da Vitória', 16121);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (155, 'Leigha', 'Hofton', 'Midfielder', 'Amorim', 18562);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (156, 'Cathi', 'Foxton', 'Attacker', 'Al Qūşīyah', 19792);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (157, 'Sanders', 'Corner', 'Midfielder', 'Tubalan', 4942);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (158, 'Ashli', 'Gipps', 'Defender', 'Nenagh', 17935);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (159, 'Bathsheba', 'Millar', 'Goalkeeper', 'Tidaholm', 10637);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (160, 'Matty', 'Witnall', 'Attacker', 'Taipei', 13476);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (161, 'Vida', 'D''Adda', 'Defender', 'Kyustendil', 8098);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (162, 'Stepha', 'Barnson', 'Attacker', 'Dakoutun', 11579);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (163, 'Cliff', 'Simao', 'Attacker', 'Xinhang', 19987);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (164, 'Merla', 'Thomkins', 'Midfielder', 'Jalal-Abad', 11163);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (165, 'Michele', 'Butterfield', 'Midfielder', 'Nagbukel', 9117);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (166, 'Rafaelita', 'Chin', 'Goalkeeper', 'Mawza‘', 9910);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (167, 'Vittoria', 'Bradly', 'Goalkeeper', 'Osnabrück', 11107);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (168, 'Carson', 'Tremouille', 'Attacker', 'Rumat Heib', 15029);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (169, 'Crysta', 'Henker', 'Defender', 'Sagarejo', 4201);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (170, 'Barbara-anne', 'Farren', 'Attacker', 'Santa Elena', 16407);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (171, 'Herminia', 'Coenraets', 'Midfielder', 'Jiangcheng', 16719);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (172, 'Cornall', 'Simononsky', 'Attacker', 'Zhongxing', 15321);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (173, 'Cicely', 'Ord', 'Goalkeeper', 'Rawa', 19516);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (174, 'Katha', 'Schollar', 'Attacker', 'Brive-la-Gaillarde', 8041);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (175, 'Clevey', 'MacCostye', 'Midfielder', 'Jatiraya', 12628);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (176, 'Gweneth', 'Goudge', 'Goalkeeper', 'Quinta', 16333);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (177, 'Ed', 'Figin', 'Attacker', 'Ivry-sur-Seine', 11986);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (178, 'Agace', 'Sprigg', 'Defender', 'Salt Lake City', 7685);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (179, 'Rosabel', 'Lowdwell', 'Defender', 'Ndendé', 18915);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (180, 'Mame', 'Roberti', 'Attacker', 'Zhangqiang', 7304);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (181, 'Tammy', 'Chatburn', 'Goalkeeper', 'Yucun', 17095);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (182, 'Janos', 'Jeanes', 'Goalkeeper', 'Brezovica', 11228);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (183, 'Benedict', 'Sandercock', 'Midfielder', 'Zarichne', 14302);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (184, 'Arlan', 'Rodnight', 'Goalkeeper', 'Sarmīn', 6553);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (185, 'Hyman', 'Giacomello', 'Attacker', 'Hacienda La Calera', 12342);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (186, 'Joletta', 'Espada', 'Defender', 'Gayny', 4134);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (187, 'Sioux', 'Dafter', 'Defender', 'Byumba', 15128);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (188, 'Arleen', 'Counihan', 'Goalkeeper', 'Wanzhi', 4431);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (189, 'Vincenz', 'Loram', 'Midfielder', 'Túquerres', 4761);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (190, 'Sanderson', 'Breckon', 'Goalkeeper', 'Cruzeiro do Sul', 8221);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (191, 'Annelise', 'Broad', 'Midfielder', 'Adrasmon', 18858);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (192, 'Conny', 'Bau', 'Goalkeeper', 'Chirkey', 15722);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (193, 'Talya', 'Prestie', 'Defender', 'Khok Charoen', 19653);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (194, 'Lurlene', 'Ashfield', 'Defender', 'Huancaray', 10754);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (195, 'Stephani', 'MacAllister', 'Defender', 'Dongqianhu', 19821);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (196, 'Jillian', 'Wainman', 'Goalkeeper', 'Podporozh’ye', 7087);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (197, 'Letitia', 'Treherne', 'Attacker', 'Tougan', 9821);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (198, 'Harwell', 'Dimblebee', 'Midfielder', 'Cochabamba', 10380);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (199, 'Harris', 'Gewer', 'Goalkeeper', 'Skillingaryd', 4525);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (200, 'Sybil', 'Geist', 'Midfielder', 'Cabinda', 13206);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (201, 'Levey', 'Itzkovitch', 'Goalkeeper', 'Sindangsuka', 16402);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (202, 'Myer', 'Hercules', 'Goalkeeper', 'Puerto Cisnes', 12621);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (203, 'Vilhelmina', 'Hoffman', 'Defender', 'Labuan', 18785);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (204, 'Kara-lynn', 'Swarbrick', 'Defender', 'Herby', 7415);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (205, 'Danya', 'Grolmann', 'Attacker', 'Semiring', 11656);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (206, 'Tibold', 'Parcall', 'Goalkeeper', 'Krzemienica', 10078);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (207, 'Lars', 'Sharply', 'Defender', 'Ḩalāwah', 4143);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (208, 'Koo', 'Alessandrini', 'Goalkeeper', 'Chyňava', 16753);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (209, 'Audrey', 'Filinkov', 'Defender', 'Girihieum', 16868);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (210, 'Dorothy', 'Gutch', 'Defender', 'Opinogóra Górna', 16096);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (211, 'Malia', 'Caret', 'Defender', 'Matango', 19036);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (212, 'Ivor', 'Mohammad', 'Defender', 'Horní Cerekev', 6412);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (213, 'Louie', 'Rennie', 'Attacker', 'Sagang', 10035);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (214, 'Iosep', 'Gusticke', 'Attacker', 'Novozavedennoye', 16259);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (215, 'Fiann', 'Ramas', 'Attacker', 'Lixin', 4025);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (216, 'Josefa', 'Gilhouley', 'Attacker', 'Pacet', 10415);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (217, 'Dian', 'Shearer', 'Defender', 'Hörby', 14520);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (218, 'Ricardo', 'McKeurtan', 'Attacker', 'Manhush', 19036);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (219, 'Fleurette', 'O''Dunneen', 'Midfielder', 'Clervaux', 10687);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (220, 'Eddie', 'Huxham', 'Attacker', 'Hradec Králové', 14614);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (221, 'Thacher', 'Pizer', 'Attacker', 'Linglu', 10344);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (222, 'Lindy', 'Norssister', 'Goalkeeper', 'Bukor', 7924);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (223, 'Roda', 'Joyner', 'Goalkeeper', 'Barra', 19378);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (224, 'Samuele', 'Tolland', 'Attacker', 'Nueva Gorgona', 18776);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (225, 'Camille', 'Grew', 'Attacker', 'Bantiran', 17222);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (226, 'Clark', 'Else', 'Attacker', 'Zhongnan', 12723);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (227, 'Junina', 'Gebbie', 'Midfielder', 'Straldzha', 4052);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (228, 'Lanie', 'Limbourne', 'Midfielder', 'Alabat', 9957);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (229, 'Lief', 'Jessop', 'Defender', 'Zalanga', 16736);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (230, 'Ruggiero', 'Hawket', 'Defender', 'Gori', 11942);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (231, 'Burtie', 'Maynell', 'Goalkeeper', 'El Rosario', 7557);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (232, 'Rica', 'Davidofski', 'Defender', 'Lexington', 15563);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (233, 'Roberto', 'Phin', 'Goalkeeper', 'Baraya', 7948);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (234, 'Gran', 'Hirtzmann', 'Attacker', 'Santa Cruz', 14951);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (235, 'Delphinia', 'Beadles', 'Attacker', 'Linton', 9786);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (236, 'Nissie', 'Tribble', 'Attacker', 'Koga', 14255);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (237, 'Iseabal', 'Kinloch', 'Midfielder', 'Vitebsk', 13838);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (238, 'Bourke', 'Stearn', 'Goalkeeper', 'Panaoti', 6771);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (239, 'Symon', 'Witson', 'Goalkeeper', 'Raphoe', 18347);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (240, 'Bren', 'O''Heaney', 'Goalkeeper', 'Najiaying', 13589);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (241, 'Reba', 'Sheer', 'Defender', 'Shijiazhuang', 11897);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (242, 'Malvin', 'Hanne', 'Defender', 'Agara', 12963);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (243, 'Paulo', 'Bouchard', 'Defender', 'Hamburg', 10183);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (244, 'Waylin', 'Breston', 'Attacker', 'Airmolek', 13992);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (245, 'Gael', 'Jacquest', 'Midfielder', 'Varnávas', 14806);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (246, 'Mathilda', 'Greiser', 'Goalkeeper', 'Eirol', 19116);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (247, 'Hendrick', 'Saiens', 'Defender', 'Puszczykowo', 14338);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (248, 'Marianne', 'Usher', 'Attacker', 'Kishk-e Nakhūd', 8335);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (249, 'Cross', 'Woodroffe', 'Defender', 'Tangnan', 15030);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (250, 'Alicia', 'Mouatt', 'Defender', 'Kutamangu', 5867);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (251, 'Tobi', 'Garrettson', 'Goalkeeper', 'Sedayulawas', 6465);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (252, 'Hanna', 'Jotham', 'Midfielder', 'Trawniki', 4609);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (253, 'Joleen', 'Top', 'Attacker', 'Liangdong', 12832);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (254, 'Oswell', 'Rice', 'Attacker', 'Kafr Şūr', 4964);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (255, 'Teddy', 'Simkins', 'Goalkeeper', 'Piteå', 10627);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (256, 'Fannie', 'Cairney', 'Defender', 'Karatau', 10397);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (257, 'Rebeka', 'Billsberry', 'Defender', 'Fukuyama', 8208);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (258, 'Welby', 'Cato', 'Defender', 'Dalongdong', 15146);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (259, 'Holden', 'Pratt', 'Midfielder', 'Heiheba', 9838);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (260, 'Ermina', 'Gooddy', 'Attacker', 'Cerro', 8847);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (261, 'Hillery', 'Winney', 'Midfielder', 'Lykóvrysi', 13917);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (262, 'Conrad', 'Garton', 'Goalkeeper', 'Raheny', 10717);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (263, 'Jonis', 'Gamlyn', 'Defender', 'Otradnoye', 12428);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (264, 'Anthiathia', 'Bush', 'Attacker', 'Lamphun', 6743);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (265, 'Sumner', 'Ilchuk', 'Goalkeeper', 'Liusi', 10027);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (266, 'Janella', 'Latour', 'Midfielder', 'Dambulla', 10120);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (267, 'Nerissa', 'Hasselby', 'Midfielder', 'Battung', 4790);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (268, 'Geordie', 'Pryer', 'Goalkeeper', 'Laraos', 5994);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (269, 'Lindy', 'Ragbourn', 'Attacker', 'Atikokan', 19350);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (270, 'Trace', 'Tonn', 'Defender', 'Church End', 4683);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (271, 'Kym', 'Scotchbrook', 'Defender', 'Poteran', 12925);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (272, 'Ami', 'Pound', 'Attacker', 'Girijaya', 16539);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (273, 'Kerri', 'Sacks', 'Attacker', 'Ribeira do Pombal', 14622);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (274, 'Stanton', 'Nizet', 'Attacker', 'Thành Phố Nam Định', 12486);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (275, 'Rodie', 'Smitham', 'Defender', 'San Bernardo', 6221);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (276, 'Melantha', 'Balfre', 'Defender', 'San Juan Sacatepéquez', 11890);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (277, 'Jaine', 'Gartrell', 'Midfielder', 'Aknīste', 19278);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (278, 'Niki', 'Bosche', 'Attacker', 'Tagasilay', 7319);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (279, 'Maurizio', 'Snelling', 'Goalkeeper', 'Boticas', 18243);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (280, 'Ulrich', 'Tinniswood', 'Attacker', 'Carepa', 18486);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (281, 'Idette', 'Nelius', 'Midfielder', 'Encontrados', 6147);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (282, 'Everett', 'Ruddlesden', 'Attacker', 'Kongsvinger', 11965);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (283, 'Crichton', 'McVittie', 'Defender', 'Vidnoye', 16075);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (284, 'Staci', 'Amer', 'Midfielder', 'Ciepielów', 10036);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (285, 'Florinda', 'Sawkin', 'Midfielder', 'Quatre Bornes', 5199);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (286, 'Nata', 'Wren', 'Defender', 'Shetan', 6337);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (287, 'Kara', 'Dunlop', 'Attacker', 'Xiapu', 18066);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (288, 'Lesly', 'Pollak', 'Midfielder', 'Slavonice', 9954);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (289, 'Nari', 'Zellick', 'Attacker', 'Jeremi', 13736);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (290, 'Stafani', 'Cardenoso', 'Midfielder', 'Lemland', 8891);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (291, 'Diann', 'Strettell', 'Goalkeeper', 'Tassin-la-Demi-Lune', 16050);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (292, 'Orbadiah', 'Feeley', 'Attacker', 'Schenectady', 16959);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (293, 'Kearney', 'Schwier', 'Goalkeeper', 'Erniusuokou', 5829);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (294, 'Olva', 'Aslet', 'Defender', 'Nanjiao', 15653);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (295, 'Hanny', 'Swinburn', 'Midfielder', 'Kebili', 5361);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (296, 'Cammi', 'McLoney', 'Goalkeeper', 'Okcheon', 19346);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (297, 'Thor', 'Worsnop', 'Goalkeeper', 'Zhongzuiling', 16137);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (298, 'Conny', 'Newlyn', 'Attacker', 'Tomsk', 14374);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (299, 'Lura', 'Dudding', 'Midfielder', 'Toukh', 18429);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (300, 'Terrance', 'Guitte', 'Defender', 'Ovalle', 12139);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (301, 'Florance', 'Vallis', 'Goalkeeper', 'Ulaan-Uul', 4997);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (302, 'Felike', 'Showl', 'Defender', 'Glasnevin', 15889);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (303, 'Daisy', 'Pettinger', 'Midfielder', 'Sedlarevo', 17331);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (304, 'Jaime', 'Tiffin', 'Goalkeeper', 'Shuishaping', 16468);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (305, 'Scotti', 'Drew-Clifton', 'Defender', 'Mashan', 16025);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (306, 'Taddeo', 'Flemyng', 'Defender', 'Anling', 8070);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (307, 'Brew', 'Guise', 'Defender', 'Vagos', 10706);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (308, 'Pansie', 'Mum', 'Goalkeeper', 'Wangping', 5233);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (309, 'Damian', 'Carleton', 'Goalkeeper', 'Cheongsong gun', 18366);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (310, 'Rosaline', 'Manchester', 'Attacker', 'Huanshi', 13044);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (311, 'Elfie', 'Clynter', 'Attacker', 'Santo Rosario', 6548);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (312, 'Sal', 'O''Mailey', 'Defender', 'Ouadda', 14229);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (313, 'Hendrick', 'Grinaugh', 'Attacker', 'Étampes', 14782);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (314, 'Ingeborg', 'Farahar', 'Goalkeeper', 'Cedar Rapids', 18845);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (315, 'Shaylyn', 'Cowins', 'Midfielder', 'Ocuviri', 7787);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (316, 'Christal', 'Gurrado', 'Defender', 'San Vicente de Moravia', 9199);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (317, 'Linn', 'Wadhams', 'Attacker', 'Kasamwa', 10314);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (318, 'Van', 'Blenkiron', 'Midfielder', 'Kachar', 16640);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (319, 'Gaby', 'Fields', 'Goalkeeper', 'Des Moines', 15528);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (320, 'Cristine', 'Grimster', 'Goalkeeper', 'Adstock', 7579);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (321, 'Forester', 'Kennedy', 'Goalkeeper', 'Karangsuko', 11263);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (322, 'Blinny', 'Pettigrew', 'Goalkeeper', 'Pawa', 19313);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (323, 'Gabie', 'Bagworth', 'Defender', 'Shirgjan', 13076);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (324, 'Jacquelin', 'Brummitt', 'Midfielder', 'Västra Frölunda', 15212);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (325, 'Drucill', 'Sanney', 'Attacker', '‘Awartā', 16022);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (326, 'Way', 'Towndrow', 'Defender', 'Mengxingzhuang', 17717);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (327, 'Burr', 'Garrad', 'Midfielder', 'Mayo', 7537);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (328, 'Lemuel', 'Coghlin', 'Attacker', 'Grebnevo', 6284);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (329, 'Merrilee', 'Grevile', 'Goalkeeper', 'Huainan', 5290);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (330, 'Minny', 'Beckinsale', 'Defender', 'Douz', 14291);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (331, 'Gabriela', 'Scholard', 'Defender', 'Peristerona', 8834);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (332, 'Abbe', 'Norridge', 'Attacker', 'Mstsislaw', 16788);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (333, 'Di', 'Messom', 'Midfielder', 'Xianbao', 14872);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (334, 'Callida', 'Rapier', 'Attacker', 'Pępowo', 7000);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (335, 'Conway', 'Lourens', 'Defender', 'Chinchiná', 9065);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (336, 'Barbara-anne', 'Benedit', 'Attacker', 'Seria', 19277);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (337, 'Marty', 'Chaffin', 'Midfielder', 'Acevedo', 11514);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (338, 'Ronnica', 'Ellingsworth', 'Attacker', 'Prado', 4553);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (339, 'Celestyna', 'Lynock', 'Defender', 'Manjakandriana', 11720);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (340, 'Kial', 'Collingridge', 'Defender', 'Dayr Sāmit', 12383);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (341, 'Giorgio', 'De Pietri', 'Goalkeeper', 'Buyant', 19254);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (342, 'Ann', 'Masden', 'Midfielder', 'Kano', 9165);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (343, 'Gage', 'Braithwaite', 'Goalkeeper', 'Lidoríki', 16811);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (344, 'Yetty', 'Underhill', 'Defender', 'Krebet', 11619);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (345, 'Benedicta', 'Olivella', 'Goalkeeper', '‘Abbāsābād', 13816);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (346, 'Romola', 'Munford', 'Midfielder', 'Guagua', 12141);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (347, 'Jan', 'Danbye', 'Attacker', 'Kampungladang', 18584);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (348, 'Brian', 'Conley', 'Attacker', 'Tsovazard', 7930);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (349, 'Friedrick', 'Tooth', 'Goalkeeper', 'Verkhniy Landekh', 7022);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (350, 'Oswald', 'MacGuigan', 'Defender', 'Huddinge', 6954);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (351, 'Gusti', 'Fearneley', 'Goalkeeper', 'Pajeksan', 13498);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (352, 'Yvette', 'Titheridge', 'Attacker', 'Severnyy', 10675);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (353, 'Ashby', 'Janney', 'Midfielder', 'Qintong', 6372);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (354, 'Seumas', 'Spottswood', 'Defender', 'Bendosewu', 4170);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (355, 'Abdul', 'Brownsall', 'Midfielder', 'Papelón', 13510);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (356, 'Milty', 'Louth', 'Goalkeeper', 'Yurino', 10507);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (357, 'Galvin', 'Wiltsher', 'Defender', 'Medina', 12558);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (358, 'Bianca', 'Menhci', 'Goalkeeper', 'Liangzeng', 9347);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (359, 'Brand', 'Goldfinch', 'Defender', 'Higashimurayama-shi', 14021);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (360, 'Petronia', 'Turfes', 'Midfielder', 'Szeged', 16318);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (361, 'Kaspar', 'Flowerden', 'Attacker', 'Kananga', 7867);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (362, 'Mellisent', 'Proudley', 'Goalkeeper', 'Long’anqiao', 4491);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (363, 'Jesse', 'Tresise', 'Attacker', 'Gandajika', 12278);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (364, 'Liuka', 'Hauxley', 'Goalkeeper', 'Miki', 17732);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (365, 'Mallory', 'Spleving', 'Defender', 'Volodarsk', 19656);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (366, 'Alyce', 'Blowen', 'Midfielder', 'Amaraji', 12176);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (367, 'Shoshanna', 'Doylend', 'Attacker', 'Aytos', 12830);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (368, 'Dorothea', 'Cashmore', 'Defender', 'Maple Creek', 10261);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (369, 'Burtie', 'Yeandel', 'Midfielder', 'Pecna', 15793);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (370, 'Donetta', 'Thouless', 'Defender', 'Carquefou', 7546);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (371, 'Blaine', 'Tootell', 'Attacker', 'Krapyak Kidul', 12269);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (372, 'Morissa', 'Cready', 'Goalkeeper', 'Dallas', 4435);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (373, 'Lyndsie', 'Bernardos', 'Midfielder', 'Gunem', 13161);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (374, 'Kaylyn', 'Whellans', 'Attacker', 'Guabito', 19976);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (375, 'Edi', 'Stolting', 'Attacker', 'Kanbe', 14581);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (376, 'Wanda', 'Waldron', 'Goalkeeper', 'Bulakbanjar', 16339);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (377, 'Cori', 'Nickerson', 'Defender', 'Stari Grad', 5187);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (378, 'Roosevelt', 'Mundie', 'Attacker', 'Hamm', 11384);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (379, 'Ezmeralda', 'Farriar', 'Defender', 'Khok Sung', 15200);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (380, 'Estella', 'Glavis', 'Midfielder', 'Floresta', 18136);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (381, 'Jeddy', 'Ferrieroi', 'Attacker', 'Živinice', 4690);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (382, 'Filberto', 'Sink', 'Goalkeeper', 'Shijia', 11092);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (383, 'Cornall', 'Stourton', 'Midfielder', 'Kabare', 5777);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (384, 'Stan', 'Leere', 'Goalkeeper', 'Ryazanskiy', 4158);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (385, 'Teri', 'Riquet', 'Attacker', 'Sopo', 11566);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (386, 'Bellanca', 'Clewes', 'Midfielder', 'Miaofengshan', 18939);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (387, 'Ag', 'Milborn', 'Goalkeeper', 'Daidaon', 19251);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (388, 'Pattin', 'Hanway', 'Attacker', 'Weishui', 16009);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (389, 'Alicea', 'Goodreid', 'Defender', 'Majie', 6240);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (390, 'Isak', 'Gillie', 'Defender', 'Julita', 17689);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (391, 'Roby', 'Swindell', 'Midfielder', 'Jialu', 18238);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (392, 'Millie', 'Binestead', 'Midfielder', 'Qiaonan', 8180);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (393, 'Rachael', 'Mochar', 'Goalkeeper', 'Melchor Ocampo', 6164);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (394, 'Cross', 'Lelande', 'Goalkeeper', 'Quebradas', 10076);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (395, 'Tallulah', 'Farington', 'Attacker', 'Charlottenberg', 8111);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (396, 'Arabela', 'Swindles', 'Goalkeeper', 'Bonneuil-sur-Marne', 8355);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (397, 'Pat', 'Dewar', 'Attacker', 'Hyltebruk', 4077);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (398, 'Ganny', 'Menzies', 'Defender', 'Além do Rio', 13800);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (399, 'Hollie', 'Doole', 'Goalkeeper', 'Sendai-shi', 12088);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (400, 'Dulsea', 'Hagergham', 'Defender', 'Medenine', 7708);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (401, 'Vincenz', 'Physick', 'Defender', 'Cloyne', 10926);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (402, 'Jock', 'Silvester', 'Defender', 'Karawatu', 19433);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (403, 'Lyssa', 'Haythornthwaite', 'Attacker', 'Niquero', 14417);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (404, 'Edsel', 'Treeby', 'Defender', 'Séguéla', 12220);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (405, 'Sayers', 'Skoggins', 'Defender', 'Shangrao', 17541);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (406, 'Enos', 'Hacket', 'Midfielder', 'Challans', 4128);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (407, 'Elie', 'Pastor', 'Midfielder', 'Yayao', 9597);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (408, 'Bealle', 'Stredwick', 'Midfielder', 'Lobuk', 7123);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (409, 'Carmina', 'Pickover', 'Midfielder', 'Cinyawar', 5598);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (410, 'Rodney', 'Gaish', 'Attacker', 'Taraju', 9952);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (411, 'Ingamar', 'Jakoubec', 'Defender', 'Solna', 4323);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (412, 'Marwin', 'Dyzart', 'Defender', 'Ban Na Muang', 12664);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (413, 'Dawna', 'Rablin', 'Attacker', 'Puerto Francisco de Orellana', 19158);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (414, 'Paige', 'Pettecrew', 'Midfielder', 'As Sawdā', 11659);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (415, 'Priscella', 'Jonah', 'Midfielder', 'Cabudare', 7450);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (416, 'Raven', 'Ellsom', 'Defender', 'Duwaktenggi', 14895);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (417, 'Nelia', 'Penrose', 'Attacker', 'Gongju', 9959);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (418, 'Margalit', 'Houtbie', 'Attacker', 'Strawczyn', 7523);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (419, 'Nadia', 'Beatty', 'Attacker', 'Apucarana', 17232);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (420, 'Fredrick', 'Petrussi', 'Goalkeeper', 'Mbanza-Ngungu', 6928);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (421, 'Heriberto', 'Pollie', 'Defender', 'Khānaqāh', 10323);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (422, 'Kerstin', 'Greenhalgh', 'Attacker', 'Zavolzh’ye', 6049);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (423, 'Ondrea', 'Atrill', 'Goalkeeper', 'Zhaodong', 5621);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (424, 'Way', 'Harefoot', 'Defender', 'Peza e Madhe', 13914);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (425, 'Meara', 'Wragg', 'Defender', 'Lyon', 13807);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (426, 'Dido', 'Koenen', 'Attacker', 'Bom Jesus da Lapa', 16732);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (427, 'Carlee', 'Nancekivell', 'Attacker', 'Yelizavetinskaya', 7532);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (428, 'Rollo', 'Ditchburn', 'Goalkeeper', 'Sarilhos Grandes', 10207);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (429, 'Nerita', 'Pheasey', 'Attacker', 'Nanhuang', 8163);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (430, 'Thoma', 'Jefferd', 'Midfielder', 'Azinhal', 12976);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (431, 'Augy', 'Reddlesden', 'Midfielder', 'Tibati', 5739);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (432, 'Lonnie', 'Ghirardi', 'Defender', 'Al Qanāyāt', 16757);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (433, 'Cornelius', 'Charlick', 'Goalkeeper', 'Matou', 4205);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (434, 'Belinda', 'Haugen', 'Defender', 'Mawlamyine', 8358);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (435, 'Honoria', 'Hatz', 'Midfielder', 'Ma’ao', 17188);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (436, 'Tierney', 'Gyorgy', 'Defender', 'Osoyoos', 4494);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (437, 'Roarke', 'Mervyn', 'Goalkeeper', 'Linzi', 4668);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (438, 'Bartholomew', 'Scott', 'Defender', 'San Antonio', 16433);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (439, 'Correy', 'Gilfillan', 'Midfielder', 'Belém', 4788);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (440, 'Jamal', 'Quartley', 'Goalkeeper', 'Akat Amnuai', 15773);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (441, 'Claudina', 'Coulsen', 'Goalkeeper', 'Yélimané', 12589);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (442, 'Jeddy', 'Oxborough', 'Midfielder', 'Changjiang', 11351);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (443, 'Valaria', 'Twine', 'Defender', 'Qohord-e Bālā', 5952);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (444, 'Lewie', 'Piner', 'Goalkeeper', 'Malya', 16881);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (445, 'Camille', 'Pilipets', 'Defender', 'Lazo', 16747);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (446, 'Polly', 'Haly', 'Midfielder', 'Houston', 14614);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (447, 'Bartlet', 'Ferencz', 'Midfielder', 'Ogawa', 18291);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (448, 'Doloritas', 'Ivantsov', 'Attacker', 'Puor', 18058);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (449, 'Dorris', 'Muschette', 'Midfielder', 'Luleå', 9954);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (450, 'Corbett', 'Craise', 'Defender', 'Ventanas', 19912);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (451, 'Cindelyn', 'Mawford', 'Goalkeeper', 'Pristina', 18437);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (452, 'Sarina', 'McNelly', 'Defender', 'Nantes', 18002);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (453, 'Bambie', 'Bromfield', 'Defender', 'Gondar', 19718);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (454, 'Carrie', 'Luxton', 'Attacker', 'Janowice', 10536);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (455, 'Ric', 'Donisi', 'Attacker', 'Bodeh', 15667);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (456, 'Fancy', 'Tedder', 'Defender', 'Kirzhach', 10148);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (457, 'Benjamen', 'Mazey', 'Midfielder', 'Ancol', 17740);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (458, 'Antons', 'Cudde', 'Goalkeeper', 'Huanggang', 15291);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (459, 'Giustino', 'Hardman', 'Attacker', 'San Agustin', 17168);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (460, 'Devan', 'Costelloe', 'Midfielder', 'Hamm', 13460);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (461, 'Amalita', 'Ussher', 'Midfielder', 'La Roche-sur-Yon', 6312);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (462, 'Sib', 'Goering', 'Defender', 'Ribeira', 9448);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (463, 'Luther', 'Maps', 'Defender', 'Rama', 12692);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (464, 'Saundra', 'Shuttle', 'Goalkeeper', 'Ceibas', 14353);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (465, 'Marnia', 'Flaubert', 'Goalkeeper', 'Ishige', 16307);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (466, 'Ted', 'de Guerre', 'Goalkeeper', 'Liên Chiểu', 11168);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (467, 'Fremont', 'Cherrington', 'Goalkeeper', 'Marseille', 18198);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (468, 'Byrom', 'Goodnow', 'Midfielder', 'Yanbei', 10732);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (469, 'Nettie', 'MacKegg', 'Midfielder', 'Bothaville', 9594);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (470, 'Aprilette', 'Hartmann', 'Midfielder', 'Ogod', 5019);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (471, 'Redd', 'Aldrin', 'Midfielder', 'Lindi', 13269);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (472, 'Goldina', 'Thunnercliff', 'Attacker', 'Detroit', 12544);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (473, 'Lita', 'Franssen', 'Goalkeeper', 'Velká Bíteš', 9781);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (474, 'Barnabe', 'Evershed', 'Midfielder', 'Teutônia', 8810);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (475, 'Emlynne', 'Lebang', 'Attacker', 'Sanyi', 10998);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (476, 'Fielding', 'Bainbridge', 'Attacker', 'Tongkiling', 11465);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (477, 'Grace', 'Debill', 'Attacker', 'Montpellier', 17908);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (478, 'Brandi', 'Kirkby', 'Attacker', 'Sapouy', 18959);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (479, 'Bradan', 'Souten', 'Defender', 'Ngeru', 8765);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (480, 'Arri', 'Knath', 'Defender', 'Tumcon Ilawod', 9943);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (481, 'Jacky', 'Ratt', 'Midfielder', 'Sipoholon', 16469);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (482, 'Mozelle', 'Serot', 'Midfielder', 'Lárdos', 6740);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (483, 'Chery', 'Duxbarry', 'Goalkeeper', 'Tashi', 15646);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (484, 'Woodrow', 'Blackater', 'Attacker', 'Blimbing', 19759);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (485, 'Chlo', 'MacClenan', 'Defender', 'San Andres', 8758);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (486, 'Violante', 'Tather', 'Midfielder', 'Taranovskoye', 18658);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (487, 'Menard', 'Brunskill', 'Attacker', 'Libacao', 10957);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (488, 'Nerissa', 'Guerreiro', 'Midfielder', 'Haruman', 13124);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (489, 'Indira', 'Sebborn', 'Midfielder', 'Kupahandap', 10008);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (490, 'Chloette', 'Udall', 'Midfielder', 'Kuanghe', 4748);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (491, 'Davon', 'Brugh', 'Goalkeeper', 'Kahnūj', 6803);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (492, 'Nicholas', 'Matzeitis', 'Goalkeeper', 'Ajax', 4884);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (493, 'Suellen', 'Fooks', 'Goalkeeper', 'Radeče', 7575);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (494, 'Nilson', 'McCann', 'Midfielder', 'Ganquan', 15688);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (495, 'Pascal', 'Dunsmore', 'Goalkeeper', 'Calgary', 11912);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (496, 'Erasmus', 'Cleaver', 'Defender', 'Malakand', 6129);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (497, 'Maribeth', 'Brosi', 'Goalkeeper', 'Babirik', 4187);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (498, 'Miles', 'Yablsley', 'Defender', 'Zhangcaizhuang', 8407);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (499, 'Marion', 'Lerego', 'Attacker', 'Markópoulo', 5372);
insert into PLAYERS (Player_ID, First_Name, Last_Name, Position, Team_Name, Current_Price) values (500, 'Juieta', 'Bunney', 'Defender', 'Izra‘', 12889);


-- rounds table generate with 500 records


